name: JamesMeadowcroft
favicon: null
layout_spectrum: 0.5584
typography_spectrum: 0.26655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#aa7e40'
    - '#333635'
    - '#406263'
    - '#d6cebe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
